### ISSUE TITLE
[BUG] Vods are buffering every 10 seconds

### ISSUE THREAD

**Issue by zameermotalib** [vod-friends/lirik.tv#13]
**Describe the bug**
When I try to watch someone's twitch vods (LIRIK) I notice that every 10 seconds it starts to lag and shows a loading screen as attached. I know that it is not my internet connection as I have not have any connection problem on any site and my internet speed is pretty good. Do you'll know what is causing the problem and what I can do to overcome it. This is on the https://lirik.tv/ website and has happened on many vods I have come across with (Old and new). I have noticed that some (Random) vods load  like a YouTube video as attached and these videos run smoothly with no lag. Is it possible to make all Vods run like this.

**To Reproduce**
1. Go to https://lirik.tv/
2. Click on any random Vod and make sure that its not loaded as a YouTube video
3. Will notice buffering

**Expected behavior**

**Screenshots**
Image of it buffering and not loading as a YouTube video.
![image](https://user-images.githubusercontent.com/49324578/133567360-81b3362c-7440-46de-9563-e8d6d8244ce6.png)

Vod that loads as a YouTube video
![image](https://user-images.githubusercontent.com/49324578/133567726-17c1247a-47d6-45e6-9b8b-c489fb17457f.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - Browser Chrome
 - Version

**Comment by Daniele122898** [comment]
Hi,
An update featuring a new HLS player is planned in the future. No ETA yet but sometime in the near future. That should in theory provide smoother playback and less buffering. I will update this issue once said player is implemented. Excuse the delay and problems
