### ISSUE TITLE
[BUG] Chat messages doubling

### ISSUE THREAD

**Issue by neoccccc** [vod-friends/lirik.tv#19]
**Describe the bug**
Chat message is doubling

**To Reproduce**
VOD title 
[1292502020] February 9th 2022 (Wednesday) | lirik.tv
link:
https://lirik.tv/vod/7ad70701-b39c-4d23-bd56-dadff32a5051

**Screenshots**
![bug](https://user-images.githubusercontent.com/4793962/153802933-9e3b3bda-2c63-43d9-a3ce-28b772cb544a.png)

**Desktop (please complete the following information):**
Win10, Chrome Version 98.0.4758.82 (Official Build) (64-bit) with adblock addons disabled. 

**Additional context**

**Comment by jonrainier** [comment]
Fixed!
