### ISSUE TITLE
[BUG] Chat messages doubling

### ISSUE THREAD

**Issue by mcapala** [vod-friends/lirik.tv#20]
**Describe the bug**

**To Reproduce**
1. Enter vod https://lirik.tv/vod/d56ba1e3-c929-4d3c-a49c-6522b35b88a0
2. Wait for messages on chat to appear
3. They are doubled

**Expected behavior**
Messages not to be doubled.

**Screenshots**
![obraz](https://user-images.githubusercontent.com/18419283/162575489-2d8f0de3-7b11-42d1-8467-f2d5dce84f51.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Tested on Firefox and Chrome - same issue
 - Version Firefox - 99, chrome 100.0.4896.75

**Additional context**
Same issue as in #19

**Comment by jonrainier** [comment]
Fixed, removed 130k dupes.
