### ISSUE TITLE
[BUG] Some VODs get stuck loading at specific times

### ISSUE THREAD

**Issue by Aayu1254** [vod-friends/lirik.tv#23]
**Description of bug**
Some vods get stuck at a specific timestamp. It resumes playing an stops buffering if you forward a little. Found it happening in multiple vods(not necessarily all of them). Its like a corrupted segment.

**To Reproduce**
1. Go to lirik.tv and search vampire survivors.
2. Click on the game poster.
3. Open the vod dated 01/23/2022
4. Forward to 4:21:40

**Expected behavior**
It starts(and keeps) buffering at exactly 4:21:50 without loading any further. You forward a little and it loads and resumes playing again.

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version 105.0.5195.127 (Official Build) (64-bit)
 - Also tried with Brave and Opera

**Comment by jonrainier** [comment]
When the vod was downloaded, it looks like a certain MPEG-TS part was corrupted and causes the player to bug out. Looks like a bug in our current player and currently looking for a better alternative. Thanks for letting us know!
