### ISSUE TITLE
[BUG]  Search for video using keywords Sub Sunday not working on either Chrome or Firefox

### ISSUE THREAD

**Issue by dante0905** [vod-friends/lirik.tv#24]
**Describe the bug**
Was trying to search for all Sub Sunday videos, previously was able to search for keyword Sunday

But the search seems broken now doesn't work for the keyword Sunday anymore

is there any other way to filter just Sub sunday games?

**To Reproduce**
- Try to search for the keyword Sunday

Refer to attached screenshot 
![Screenshot 2023-02-06 111424](https://user-images.githubusercontent.com/124552527/216893180-ada9e446-366e-4105-ab39-eecad877d677.png)

**Comment by jonrainier** [comment]
Should be good to go. Pushed a fix last week to cover this.
