### ISSUE TITLE
[BUG] Some emotes appear as broken image links

### ISSUE THREAD

**Issue by Aayu1254** [vod-friends/lirik.tv#25]
**Describe the bug**
I recently went to lirik.tv and encountered a bug where some specific emotes don't show up. (For me it was the "Hmm" emote)

**To Reproduce**
1. Go to vod dated 03/11/2023
2. Time to 00:54:00

**Screenshots**

![Screenshot (3)_LI](https://user-images.githubusercontent.com/79454297/224541097-18744a10-cde5-4263-8504-67b7588bfbb1.jpg)

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome, Brave

**Comment by jonrainier** [comment]
Fixed all emotes. Twitch changed endpoints.
