### ISSUE TITLE
7tv emotes does not show today 01/11/2023[BUG] 

### ISSUE THREAD

**Issue by Steffyska** [vod-friends/lirik.tv#28]
Hello!
7tv emotes or bttv emotes are not working on the site  https://lirik.tv/  , but work on twitch. Yesterday everything was okay. What happened, can it be fixed?
Help please as soon as possible
Ty

**Comment by jonrainier** [comment]
7TV sunsetted v2: https://github.com/SevenTV/API/issues/232

Issue is fixed - service updated to support v3.
