### ISSUE TITLE
[FEATURE] Is there a way to link a specific timestamp on a vod? 

### ISSUE THREAD

**Issue by DinSunrise** [vod-friends/lirik.tv#29]
If yes, then how would I go about it? 

If not, then is it possible to make it similar to twitch or youtube way, e.g. "www.lirik.tv/vod/vod_id&t=1h30m30s" ?

**Comment by jonrainier** [comment]
Yes, it's `skipTo` - example: https://lirik.tv/vod/d0f4becb-2a4a-43b3-a698-23eb585b95d2?skipTo=3286

It's an int after start time in seconds.
