### ISSUE TITLE
Media Cannot Be Played [BUG] 

### ISSUE THREAD

**Issue by cquerrieo** [vod-friends/lirik.tv#31]
Media Can Not Be Loaded
The media could not be loaded, either because the server or network failed or because the format is not supported.

**To Reproduce**
1. Attempt to open a video
2. See error

**Expected behavior**
I would expect the video to play.

**Screenshots**

![image](https://github.com/vod-friends/lirik.tv/assets/153096843/347e8d80-091b-4fc9-8c2d-c872d31afe82)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Chrome and Edge
![Screenshot 2023-12-06 090833](https://github.com/vod-friends/lirik.tv/assets/153096843/bded11e4-c8ef-4aa3-b44c-9d1116b66823)

**Comment by jonrainier** [comment]
Payment issue with the CDN, which is now resolved.
