### ISSUE TITLE
[FEATURE] Prefetch Playlist to Avoid Buffering

### ISSUE THREAD

**Issue by pwnoz0r** [vod-friends/lirik.tv#8]
Adding the ability to the new player in allows for buffering on slower connections. We currently only save videos using source and save them to the CDN that way. Load times are currently improved using updated proxy for CDN: 
![image](https://user-images.githubusercontent.com/1493929/123675280-89541f00-d810-11eb-9912-e305ddd1c944.png)

**Comment by jonrainier** [comment]
#16 fixes this.
