### ISSUE TITLE
[BUG] Incorrect Video Date

### ISSUE THREAD

**Issue by Mmokuin** [vod-friends/lirik.tv#9]
Videos from this month (June) are written as May, videos from May as April, etc. All videos are like that. Days are all good but month are "back by one". I don't know how to write it. :). Just look dates on videos and you will see it. 

Screenshot example - This are streams during E3 but are written as May (5/xx/2021)
https://i.imgur.com/hTEmIJf.png

My OS + browser (all newest update)
- Windows 10 
- Google Chrome (didnt tested on other browsers)

**Comment by Daniele122898** [comment]
Fixed for future update. Should be live in a matter of days. Thanks for reporting
